version: '3.4'

services:
    web:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - .:/data
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./docker/logs/nginx:/var/log/nginx
        depends_on:
            - php

    php:
        build: docker/php/
        depends_on:
            - mysql
        env_file:
            - .env
        volumes:
            - .:/data
            - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini:ro
            - ./docker/php/config/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
            - ./docker/php/config/aliases.sh:/etc/profile.d/aliases.sh:ro
            - ./docker/logs/php:/var/log

    mysql:
        image: percona:5.7
        ports:
            - 3306:3306
        env_file:
            - .env
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./docker/mysql:/var/lib/mysql
